# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: breast_dt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'breast_dt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62reast_dt.proto\x12\tbreast_dt\"\x07\n\x05\x45mpty\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x86\x01\n\x10\x42ootstrapRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x13\n\x0bleft_radius\x18\x02 \x01(\x02\x12\x18\n\x10left_cellularity\x18\x03 \x01(\x02\x12\x14\n\x0cright_radius\x18\x04 \x01(\x02\x12\x19\n\x11right_cellularity\x18\x05 \x01(\x02\"T\n\tTumorData\x12\x0e\n\x06radius\x18\x01 \x01(\x02\x12\x13\n\x0b\x63\x65llularity\x18\x02 \x01(\x02\x12\x12\n\ndrug_level\x18\x03 \x01(\x02\x12\x0e\n\x06status\x18\x04 \x01(\t\"h\n\nTumorState\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\"\n\x04left\x18\x02 \x01(\x0b\x32\x14.breast_dt.TumorData\x12#\n\x05right\x18\x03 \x01(\x0b\x32\x14.breast_dt.TumorData\".\n\x0eTherapyRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x64osage\x18\x02 \x01(\x02\x32\xdd\x01\n\x12\x44igitalTwinService\x12\x43\n\rSendBootstrap\x12\x1b.breast_dt.BootstrapRequest\x1a\x13.breast_dt.Response\"\x00\x12\x41\n\x12StreamTumorUpdates\x12\x10.breast_dt.Empty\x1a\x15.breast_dt.TumorState\"\x00\x30\x01\x12?\n\x0bSendTherapy\x12\x19.breast_dt.TherapyRequest\x1a\x13.breast_dt.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'breast_dt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_RESPONSE']._serialized_start=39
  _globals['_RESPONSE']._serialized_end=83
  _globals['_BOOTSTRAPREQUEST']._serialized_start=86
  _globals['_BOOTSTRAPREQUEST']._serialized_end=220
  _globals['_TUMORDATA']._serialized_start=222
  _globals['_TUMORDATA']._serialized_end=306
  _globals['_TUMORSTATE']._serialized_start=308
  _globals['_TUMORSTATE']._serialized_end=412
  _globals['_THERAPYREQUEST']._serialized_start=414
  _globals['_THERAPYREQUEST']._serialized_end=460
  _globals['_DIGITALTWINSERVICE']._serialized_start=463
  _globals['_DIGITALTWINSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
