syntax = "proto3";

package breast_dt;

// Servizio principale
service DigitalTwinService {
  // 1. Il Physical Twin invia i dati iniziali (Bootstrap)
  rpc SendBootstrap (BootstrapRequest) returns (Response) {}

  // 2. Unity ascolta gli aggiornamenti in tempo reale (Streaming dal Server)
  rpc StreamTumorUpdates (Empty) returns (stream TumorState) {}

  // 3. Unity o la Pompa inviano comandi di terapia
  rpc SendTherapy (TherapyRequest) returns (Response) {}
}

// --- Messaggi ---

message Empty {}

message Response {
  bool success = 1;
  string message = 2;
}

message BootstrapRequest {
  string patient_id = 1;
  float left_radius = 2;
  float left_cellularity = 3;
  float right_radius = 4;
  float right_cellularity = 5;
}

message TumorData {
  float radius = 1;
  float cellularity = 2;
  float drug_level = 3;
  string status = 4;
}

message TumorState {
  double timestamp = 1;
  TumorData left = 2;
  TumorData right = 3;
}

message TherapyRequest {
  string type = 1;
  float dosage = 2;
}