# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import breast_dt_pb2 as breast__dt__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in breast_dt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DigitalTwinServiceStub(object):
    """Servizio principale
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBootstrap = channel.unary_unary(
                '/breast_dt.DigitalTwinService/SendBootstrap',
                request_serializer=breast__dt__pb2.BootstrapRequest.SerializeToString,
                response_deserializer=breast__dt__pb2.Response.FromString,
                _registered_method=True)
        self.StreamTumorUpdates = channel.unary_stream(
                '/breast_dt.DigitalTwinService/StreamTumorUpdates',
                request_serializer=breast__dt__pb2.Empty.SerializeToString,
                response_deserializer=breast__dt__pb2.TumorState.FromString,
                _registered_method=True)
        self.SendTherapy = channel.unary_unary(
                '/breast_dt.DigitalTwinService/SendTherapy',
                request_serializer=breast__dt__pb2.TherapyRequest.SerializeToString,
                response_deserializer=breast__dt__pb2.Response.FromString,
                _registered_method=True)


class DigitalTwinServiceServicer(object):
    """Servizio principale
    """

    def SendBootstrap(self, request, context):
        """1. Il Physical Twin invia i dati iniziali (Bootstrap)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTumorUpdates(self, request, context):
        """2. Unity ascolta gli aggiornamenti in tempo reale (Streaming dal Server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTherapy(self, request, context):
        """3. Unity o la Pompa inviano comandi di terapia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalTwinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBootstrap,
                    request_deserializer=breast__dt__pb2.BootstrapRequest.FromString,
                    response_serializer=breast__dt__pb2.Response.SerializeToString,
            ),
            'StreamTumorUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTumorUpdates,
                    request_deserializer=breast__dt__pb2.Empty.FromString,
                    response_serializer=breast__dt__pb2.TumorState.SerializeToString,
            ),
            'SendTherapy': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTherapy,
                    request_deserializer=breast__dt__pb2.TherapyRequest.FromString,
                    response_serializer=breast__dt__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'breast_dt.DigitalTwinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('breast_dt.DigitalTwinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DigitalTwinService(object):
    """Servizio principale
    """

    @staticmethod
    def SendBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/breast_dt.DigitalTwinService/SendBootstrap',
            breast__dt__pb2.BootstrapRequest.SerializeToString,
            breast__dt__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTumorUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/breast_dt.DigitalTwinService/StreamTumorUpdates',
            breast__dt__pb2.Empty.SerializeToString,
            breast__dt__pb2.TumorState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTherapy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/breast_dt.DigitalTwinService/SendTherapy',
            breast__dt__pb2.TherapyRequest.SerializeToString,
            breast__dt__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
